spring:
  datasource:
    username: vovaUniversal
    password: password
    url: jdbc:mysql://localhost:3306/fortest
  liquibase:
    change-log: classpath:db/master.xml
    enabled: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
