server:
  port: 8081

spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:test;
    driver-class-name: org.h2.Driver
  liquibase:
    change-log: classpath:db/master.xml
    enabled: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
